name: ff-cli

# library:
#   exposed: false
#   source-dirs: lib

executables:
  ff:
    dependencies:
      - directory
      - filepath
      - optparse-applicative
      - monad-logger
      - mtl
      - persistent-sqlite
      - persistent-template
      - resourcet
      - text
      - xdg-basedir
    main: Main.hs
    source-dirs: exe

tests:
  test:
    dependencies:
      - containers
      - process
      - tasty
      - tasty-hunit
      - temporary
      # package
      # - ff-cli
    main: Main.hs
    source-dirs: test

dependencies:
  - base
